### ISSUE TITLE
non-GNU sed

### ISSUE THREAD

**Issue by glickmac** [sejmodha/MiscScripts#1]
Thank you for putting this script together! To overcome a KeyError: 'taxid' if you are using a Mac, simply change the subprocess.calls in line 79 and 80 from 

`subprocess.call("sed -i '1d' assembly_summary_refseq.txt", shell=True)
    subprocess.call("sed -i 's/^# //' assembly_summary_refseq.txt", shell=True)`  

to 

`subprocess.call("sed -i.bu '1d' assembly_summary_refseq.txt", shell=True)
    subprocess.call("sed -i.bu 's/^# //' assembly_summary_refseq.txt", shell=True)`

The addition of the -i.bu creates a backup and operates sed "in place" something that is not standard on a Mac non-GNU version of sed.

**Comment by sejmodha** [comment]
Thanks for pointing this out.
