### ISSUE TITLE
Error in using the database 

### ISSUE THREAD

**Issue by vappiah** [sejmodha/MiscScripts#4]
Hi @sejmodha . I used your script to successfully setup the kraken database

But when I run I get this error
kraken: database ("/opt/apps/bioinfo/databases/kraken") does not contain necessary file database.kdb

This is the code I used
DB=/opt/apps/bioinfo/databases/kraken
kraken --preload --db $DB  sample.trimmed.fa --threads 15 --classified-out sample.classified --unclassified-out sample.unclassified > sample.kraken

Please advice

**Comment by vappiah** [comment]
I got it now. Apparently the script creates a subfolder  HumanVirusBacteria which contains the database. Once I specified that it worked.

I suggest you add that info to your main page. Thanks for the script once again.

**Comment by sejmodha** [comment]
Thanks for pointing this out. I have updated the README file.

**Comment by sejmodha** [comment]
Thanks for pointing this out. I have updated the README file.
